# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
name: BoboBot automated
 
on: push

env:
  TYPE: build
  TZ: Asia/Manila
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 525600

    steps:
       - name: Checkouts
         uses: actions/checkout@master
     # Cleanup The Actions Workspace Using Custom Composite Run Actions
       - uses: rokibhasansagar/slimhub_actions@main

         
       - name: Initializing environment
         continue-on-error: true
         timeout-minutes: 100
         run: |
              sudo -E apt-get -qq update
              sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect aria2
              git config --global user.name "nnippon"
              git config --global user.email "adameyyad999@gmail.com"
              git clone --recurse-submodules https://github.com/nnippon/ErfanGSIs
     
       - name: Setup Erfan Tools
         continue-on-error: true
         timeout-minutes: 10
         run: |
              sudo chmod -R 0777 ErfanGSIs
              sudo bash ErfanGSIs/setup.sh
       - name: Generate config.prop
         continue-on-error: true
         timeout-minutes: 3
         run: |
              java -jar Bobo.jar
